### ISSUE TITLE
Building scipy with PyPy fails on windows

### ISSUE THREAD

**Issue by mattip** [mesonbuild/meson#10080]
The [error](https://github.com/mattip/scipy/runs/5450598923?check_suite_focus=true#step:9:57) is 
> Could not find Python3 library 'c:\\hostedtoolcache\\windows\\pypy\\3.8.12\\x86\\python38.dll'

The correct dll name is `libpypy3-c.dll`, but shouldn't the compiler be MSVC and the library it is looking for be the MSVC import library which is `c:\\hostedtoolcache\\windows\\pypy\\3.8.12\\x86\\libs\python3.8.lib` (like CPython)?

**Comment by tristan957** [comment]
Is this fixed with the PR that got merged?

**Comment by mattip** [comment]
It seems not. I [reset the PR](https://github.com/mattip/scipy/runs/5461997995?check_suite_focus=true#step:7:83) to use meson HEAD, and am still getting the same error (scroll down to the bottom of that log).

I am willing to submit a patch to fix this, but would like to reproduce locally. Is there a guide to running tests? I tried on windows 10 with
```
git clone https://github.com/mesonbuild/meson
cd meson
python run_tests.py
```

Where `python` is either CPython 3.8 or PyPy 3.8, and in both cases I get many dialog boxes with the error message 
> Entry Point Not Found : The procedure entry point _ZNSt13runtime_erroraSEOS_ could not be located in the dynamic link library C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\ccache.exe

even though that mingw tools set is not on my path.

**Comment by eli-schwartz** [comment]
If CC/CXX are not set to override the compiler, the automatic detection logic will try to run `ccache --version` to see if it succeeds, then prepend it to the real compiler if it did.

So I'd suspect that for each unittest it would perform that check and fail if it found a broken ccache.exe (possibly with a Windows error dialog box explaining exactly what is broken about it) but I do not know how that could happen when that directory is not in your PATH...

**Comment by mattip** [comment]
right, sorry for the noise. That ccache.exe is broken.

**Comment by eli-schwartz** [comment]
> Is this fixed with the PR that got merged?

As mentioned in #8570 the two issues are different, because that was originally reported on Linux and is about link_libpython being false on Linux, but still leading to detection failure.

On Windows, symbols need to be resolved in built extensions, so link_libpython is true, which means that the PyPy link library does need to be found there. Hence detection failure is actually correct right now.

**Comment by eli-schwartz** [comment]
@mattip okay, so I am home now and I took a look at the implementation in `mesonbuild/modules/python.py`. I think I understand the problem.

https://github.com/mesonbuild/meson/blob/789f440f7c2bfda2e17f05ecdcb1a19245f892df/mesonbuild/modules/python.py#L129-L257

There's a couple interesting quirks here. At the heart of the detection logic is this switch between essentially two unique implementations:

```python
        if mesonlib.is_windows():
            self._find_libpy_windows(environment)
        else:
            self._find_libpy(installation, environment)
```

The inverted link_libpython check was part of find_libpy, and as you can see, that one actually checks if `python_holder.is_pypy`, then switches the library name to look for and the custom libdirs to check for it in.

`_find_libpy_windows` does none of this, but does some fairly involved logic that then dispatches checking for the library itself to `_get_windows_link_args`. This has special handling for MinGW python, regular windows python, regular windows python plus the compiler is gcc...

What it doesn't do is check for `python_holder.is_pypy` and adapt to searching for an entirely different library with an entirely different scheme.

So, that will need ~~fixing~~ initial implementation. PRs welcome, or alternatively I can write an implementation but I will need a clear description of the expected PyPy layout on Windows so that I can code it blind from on Linux.

**Comment by mattip** [comment]
I can submit a PR, but I am searching for a test that hits this code path. `pypy.exe run_unittests.py` isn't the right one.

**Comment by eli-schwartz** [comment]
In unittests/pythontests.py we try to find pypy and use it to set up `test cases/unit/39 python extmodule/`, unfortunately it's handled as a fairly ugly try/except for each version whereas it would be considerably nicer to parameterize it for each version.

(We need to support bare unittest instead of hard depending on pytest. Still, this could probably be refactored to be nicer.)

**Comment by mattip** [comment]
That test is passing in a pypy3.8 venv on HEAD
```
(venv_pypy3.8) d:\pypy_stuff\meson>python run_unittests.py PythonTests -vv
Meson build system 0.61.99 Unit Tests
pytest-xdist not found, tests will not be distributed across CPU cores
======================================================= test session starts ====
platform win32 -- Python 3.8.12[pypy-7.3.9-alpha], pytest-7.0.1, pluggy-1.0.0 -- d:\temp\venv_pypy3.8\Scripts\python.exe
cachedir: .pytest_cache
rootdir: d:\pypy_stuff\meson, configfile: setup.cfg
collected 463 items / 462 deselected / 1 selected

run_unittests.py::PythonTests::test_versions <- unittests\pythontests.py PASSED        [100%]

================================================ 1 passed, 462 deselected in 19.78s ========
Total time: 20.875 seconds
```

**Comment by eli-schwartz** [comment]
So you can also enter `test cases/unit/39 python extmodule/` and manually run `meson setup builddir -Dpython=/path/to/pypy3` and successfully build the test project and run its tests?

**Comment by eli-schwartz** [comment]
Sorry, just to clarify -- you did run ninja after running `meson setup`? It's not in your pasted console session.

**Comment by mattip** [comment]
No, I didn't know what to do after running the code above. Now I do :)
```
(venv_pypy3.8) d:\pypy_stuff\meson\test cases\unit\39 python extmodule\builddir>ninja
[2/2] Linking target ext/tachyon.pypy38-pp73-win_amd64.pyd
   Creating library ext\tachyon.pypy38-pp73-win_amd64.lib and object ext\tachyon.pypy38-pp73-win_amd64.exp

(venv_pypy3.8) d:\pypy_stuff\meson\test cases\unit\39 python extmodule\builddir>ninja test
[0/1] Running all tests.
1/1 extmod        OK              0.08s


Ok:                 1
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to d:\pypy_stuff\meson\test cases\unit\39 python extmodule\builddir\meson-logs\testlog.txt

**Comment by mattip** [comment]
Just to clarify: the test you suggested passes. How can I find one that fails like the scipy build?

**Comment by mattip** [comment]
> Is this fixed with the PR that got merged?

Something seems to have moved. Now the build gets past the configure stage, and hits a snag with the compiler flags. The [error](https://github.com/mattip/scipy/runs/5576754019?check_suite_focus=true#step:9:174) is
```
dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   39 | #define Py_INCREF(ob)   (((PyObject *)(ob))->ob_refcnt++)
```

which I thing is caused by `ccache c++ ... -Wall`. Any thoughts where the `-Wall` comes from (hint: PyPy's sysconfig is different than CPython's sysconfig, do the flags come from there)?

**Comment by eli-schwartz** [comment]
-Wall comes from Meson's core option `-Dwarning_level=1`, we don't actually use the sysconfig flags.

(I don't by and large understand the point of the sysconfig flags, because TBH there are pretty good reasons why people might want to build using different flags from the ones used to build python. Those aren't critical flags to begin with.)

**Comment by eli-schwartz** [comment]
> Something seems to have moved. Now the build gets past the configure stage, and hits a snag with the compiler flags. The [error](https://github.com/mattip/scipy/runs/5576754019?check_suite_focus=true#step:9:174) is

So that is on the Linux tests, which is good news because my PR that got merged has indeed fixed configuring with pypy on Linux.

However the Windows run still [errors out](https://github.com/mattip/scipy/runs/5576753944?check_suite_focus=true) trying to find the python dependency:

```
Could not find Python3 library 'c:\\hostedtoolcache\\windows\\pypy\\3.8.12\\x86\\python38.dll'

meson.build:52:0: ERROR: Python dependency not found
```

**Comment by eli-schwartz** [comment]
@mattip in Meson git master, you can run

```
./run_single_test.py "test cases/python/8 different python versions/"
```

and it will print something like:
```
PASS: python: 8 different python versions
PASS: python: 8 different python versions    (python=python2)
PASS: python: 8 different python versions    (python=python3)
SKIP: python: 8 different python versions    (python=pypy)
SKIP: python: 8 different python versions    (python=pypy3)
```

But in your case, since pypy3 is actually installed it should not be skipping, and having it skip will imply that detection is broken.

**Comment by mattip** [comment]
Indeed the test skips pypy and pypy3 even though they are on the path. Is there a "guide to contributing" that says how to stop at a pdb.set_trace() in tests? The test seems to be capturing stdin, stdout. Is there an option like pytest's `-s`?

**Comment by eli-schwartz** [comment]
That is a good question... I'm not sure why it skips there, actually. Can you try #10137

**Comment by eli-schwartz** [comment]
Now that #10138 is merged, the combination of Windows and GCC (msys2/mingw in other words) can correctly find the python dependency from a PyPy provider.

We also have CI covering Linux, MSVC, and mingw which validates that a simple test project builds and runs under a smoke test.

The remaining issue I think is that scipy seems to have a weird extra factor that is causing it to fail at import time with:
```
ImportError: %1 is not a valid Win32 application
```

Sadly this is not reproducible in the simple test case that our CI covers.

**Comment by mattip** [comment]
FWIW, I uploaded the bad PyPy pyd to my OneDrive [here](https://1drv.ms/u/s!AjItDERGqi8Ajh-PPJzirVCi3ujy?e=3Y1Dy4) and the corresponding good CPython pyd [here](https://1drv.ms/u/s!AjItDERGqi8Ajh6NymZ0402PpyTf) (Personally I wouldn't recommend downloading random files from random strangers). The error is reporducable on CPython by trying to `dll = ctypes.CDLL(<path_to_file.)`. The PyPy one is not valid, the CPython one correctly fails to open because of missing dependencies. I tried looking at them in depends.exe and with objdump to see what is wrong, and I couldn't find the problem.

**Comment by rgommers** [comment]
> The error is reporducable on CPython by trying to `dll = ctypes.CDLL(<path_to_file.)`.

A missing dependency in a SciPy `.pyd` library under CPython may be a bug in the SciPy build config or the GCC toolchain? If so, worth opening a SciPy issue for I think.

**Comment by mattip** [comment]
It is not a missing dependency, that shows up as a `FileNotFoundError`. This is something different: the pyd fails to load with a `ImportError: %1 is not a valid Win32 application`. In the [build log](https://github.com/mattip/scipy/runs/5988960554?check_suite_focus=true) I see where meson compiles `_ufuncs_cxx.pypy38-pp73-win_amd64.pyd` but not where it builds `_ufuncs.pypy38-pp73-win_amd64.pyd`. I cannot find the link step for any of the components. How can I see a more complete log including compilation/link flags?

**Comment by rgommers** [comment]
That build output in CI will not show anything except compile errors and (un-silenced) warnings. I think you want to look at `build/build.ninja` to obtain the link arguments. No need to run the build for that, configuring is enough.

**Comment by mattip** [comment]
It seems this may be another manifestation of the [vs14.1 problem](https://github.com/MacPython/numpy-wheels/issues/145) that was [fixed for the numpy-wheels](https://github.com/MacPython/numpy-wheels/pull/146/files). Since there is no wheel available, the PR is building NumPy from source on the CI machine, which is not using the fix, and so is more than likely using a bad npy_math.lib. This is not a meson problem, I will close this issue.
