### ISSUE TITLE
Meson is unable to find ninja (ERROR: Could not detect Ninja)

### ISSUE THREAD

**Issue by anjalirai-intel** [mesonbuild/meson#10987]
**ERROR: Could not detect Ninja**
I am trying to setup Ubuntu 22.04 for our project.

These are the versions I have in baremetal and it seems to be working fine
```
Found ninja-1.10.1 at /usr/bin/ninja
$ meson --version
0.63.3
$ ninja --version
1.10.1
$ cat /etc/os-release | grep VERSION
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
```
But when i try to replicate the same on Docker environment, I get build errors from meson
```
ERROR: Could not detect Ninja v1.8.2 or newer

$ meson --version
0.63.3
$ ninja --version
1.10.1
```
I searched about this error and it has been suggested to try installing ninja with pip3 and it should work. But i tried that and still got the same error
```
ERROR: Could not detect Ninja v1.8.2 or newer

$ meson --version
0.63.3
$ ninja --version
1.10.2.git.kitware.jobserver-1
```
So, I installed meson version 0.56.2 and ninja version 1.10.1, but when you run meson command, it ends up in error ERROR: Could not detect Ninja v1.7 or newer

**To Reproduce**
[meson.build](https://github.com/gramineproject/gramine/blob/master/meson.build)
1. Create a docker image using this dockerfile [Dockerfile](https://github.com/jinengandhi-intel/graphene_local_ci/blob/f0d9af9d2c251920dee3225c36df37c3f29efadb/ci/dockerfile/ubuntu22.04.dockerfile)
2. Start the docker container, you should be in gramine directory
3. Run this command meson setup build/ --werror --buildtype=release -Dskeleton=enabled -Ddirect=enabled -Dsgx=disabled -Dtests=enabled

**Expected behavior**
Build should be successful and in the end we should get Found ninja-1.10.1 at /usr/bin/ninja

**system parameters**
It is a plain native build 
Python Version: 3.10.6
OS: Ubuntu 22.04
Meson Version: 0.56.2
Ninja Version: 1.10.1

**Comment by anjalirai-intel** [comment]
I have put debugger inside mesonbuild/environment.py. It is able to find ninja, but it throws Permissin error, even though i have set all the permissions and i am able to execute the command from terminal


```
/usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(186)detect_ninja_command_and_version()
-> env_ninja = os.environ.get('NINJA', None)
(Pdb) n
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(187)detect_ninja_command_and_version()
-> for n in [env_ninja] if env_ninja else ['ninja', 'ninja-build', 'samu']:
(Pdb) n
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(188)detect_ninja_command_and_version()
-> prog = ExternalProgram(n, silent=True)
(Pdb) n
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(189)detect_ninja_command_and_version()
-> if not prog.found():
(Pdb) n
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(191)detect_ninja_command_and_version()
-> try:
(Pdb) n
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(192)detect_ninja_command_and_version()
-> p, found = Popen_safe(prog.command + ['--version'])[0:2]
(Pdb) prog.command
['/usr/bin/ninja']
(Pdb) n
PermissionError: [Errno 1] Operation not permitted: '/usr/bin/ninja'
> /usr/local/lib/python3.10/dist-packages/mesonbuild/environment.py(192)detect_ninja_command_and_version()
-> p, found = Popen_safe(prog.command + ['--version'])[0:2]
(Pdb) c

ERROR: Could not detect Ninja v1.7 or newer

intel@109b68536923:/home/intel/anjali/gramine$ /usr/bin/ninja --version
1.10.1

ls -al /usr/bin/ninja
-rwxrwxrwx 1 root root 248056 Aug 30  2020 /usr/bin/ninja
```

**Comment by tristan957** [comment]
Might be useful to make sure the ninja Meson detects is what you think it is.

**Comment by lazka** [comment]
See https://github.com/scikit-build/ninja-python-distributions/issues/157

**Comment by henryiii** [comment]
This is only an issue with the latest release a few hours ago, older ones were fine.

**Comment by eli-schwartz** [comment]
This also seems to be happening in a docker container that is supposed to pick up a Ubuntu-packaged version of upstream unpatched ninja, not the scikit-build patchset. So yeah, that other issue is certainly unrelated.

**Comment by eli-schwartz** [comment]
> I have put debugger inside mesonbuild/environment.py. It is able to find ninja, but it throws Permissin error, even though i have set all the permissions and i am able to execute the command from terminal

So the only thing that meson is doing differently basically seems to be "run it from python", very confusing...

If you start up a python console in the affected machine, does this work?

```python
>>> import subprocess
>>> subprocess.run(['ninja', '--version'], capture_output=True)
```

And:
```python
>>> from mesonbuild.mesonlib import Popen_safe
>>> Popen_safe(['ninja', '--version'])
```

**Comment by henryiii** [comment]
I think I'll have a patch out for the 1.11.1 issue soon. Looks like ninja 1.11.1 isn't compatible with manylinux1. Though why is it passing tests? Anyway, manylinux2010 builds don't suffer the same problem, and I can upload 2010 builds to the same release. ;)

**Comment by henryiii** [comment]
This is fixed, I believe. manylinux2010 images are working elsewhere. The manylinux1 images might get removed at some point, but they actually do work on manylinux1 I believe (since cibuildwheel's tests passed). I've also been able to reproduce the failure and the fix in CI tests.

**Comment by eli-schwartz** [comment]
Nah, still not fixed, because the original reporter wasn't using a pip installed ninja, but was using the Ubuntu packaged version without the `kitware.jobserver-1` patch. ;)

**Comment by henryiii** [comment]
Oops, sorry, was replying to all the issues, forget this one wasn't our problem. :D

**Comment by CJJLUX** [comment]
I had the same problem，Because of the “.git.kitware.jobserver-1” suffix

**problem:**
[root@d6b309491377 data]# /usr/bin/ninja --version
1.10.2

[root@d6b309491377 data]# ninja --version
1.11.1.git.kitware.jobserver-1

[root@d6b309491377 data]# which ninja
/usr/local/bin/ninja

**solve:**
cp /usr/bin/ninja /usr/local/bin/ninja

[root@d6b309491377 data]# ninja --version
1.10.2

**Comment by xclaesse** [comment]
What docker image can be used to reproduce?

**Comment by theo-dep** [comment]
I reproduce the problem on macOS 15.2 using python 3.9.6 and pip.
> ERROR: Could not detect Ninja v1.8.2 or newer

Same error using Ninja from pip (1.11.1.git.kitware.jobserver-1) or official Ninja binaries (1.11.1).

I use Meson v1.8.1 (from pip) but it is same with the Github package.

**Comment by theo-dep** [comment]
This issue is bypassed by providing an environment variable like `export NINJA=$(which ninja)` but maybe there is a bug.

**Comment by bonzini** [comment]
It shouldn't be related to the kitware suffix:

```
$ python
>>> from mesonbuild.mesonlib import version_compare
>>> version_compare('1.11.1.git.kitware.jobserver-1', '>=1.8.2')
True
```
