### ISSUE TITLE
multiple wrap files error starting with meson 1.9.0

### ISSUE THREAD

**Issue by radistmorse** [mesonbuild/meson#15175]
In my project I use a chain of subprojects that use wrap files. I put a duplicate wrap file in my top subproject folder that declare the same dependency in the `[provide]` section as the wrap file found in a subproject, but with some additional options (specify `diff_files`, change `revision` etc). With meson before 1.9.0 it worked fine: the top-level wrap file was used for subproject's subproject and the subproject's wrap file was ignored.

Starting with meson 1.9.0 I get an error `Multiple wrap files provide '<somedep>' dependency: ...`

Is this an intended behaviour or a regression? If it is intended, is there a way to specify that a top-level wrap file should take precedence over any other wrap file with the same provided dependency?

**Comment by georgev93** [comment]
I'm also having issues with this. I have a top level subproject wrap which matches a second-level subproject wrap (dependency of a different top level subproject wrap). Meson fails and prints "report this!" or something to that effect. Downgrading to 1.8.4 fixes the issue.

**Comment by bonzini** [comment]
Thanks for the report, could any of you try bisecting or provide a minimal reproducer?

**Comment by radistmorse** [comment]
<details>
<summary>diff file</summary>

```diff
diff -ruN a/meson.build b/meson.build
--- a/meson.build	1970-01-01 01:00:00.000000000 +0100
+++ b/meson.build	2025-11-03 19:12:20.935112770 +0100
@@ -0,0 +1,3 @@
+project('wraptest')
+
+subproject('subproject')
diff -ruN a/subprojects/subproject/meson.build b/subprojects/subproject/meson.build
--- a/subprojects/subproject/meson.build	1970-01-01 01:00:00.000000000 +0100
+++ b/subprojects/subproject/meson.build	2025-11-03 19:14:34.649990743 +0100
@@ -0,0 +1,3 @@
+project('subproject')
+
+dependency('foobar')
diff -ruN a/subprojects/libfoobar/meson.build b/subprojects/libfoobar/meson.build
--- a/subprojects/libfoobar/meson.build	1970-01-01 01:00:00.000000000 +0100
+++ b/subprojects/libfoobar/meson.build	2025-11-03 19:20:29.192616536 +0100
@@ -0,0 +1,3 @@
+project('foobar')
+
+foobar_dep = declare_dependency()
diff -ruN a/subprojects/test.wrap b/subprojects/test.wrap
--- a/subprojects/test.wrap	1970-01-01 01:00:00.000000000 +0100
+++ b/subprojects/test.wrap	2025-11-03 19:28:44.329223629 +0100
@@ -0,0 +1,7 @@
+[wrap-file]
+directory = libfoobar
+source_filename = foobar-1.0.tar.gz
+
+[provide]
+dependency_names=foobar
+foobar=foobar_dep
diff -ruN a/subprojects/subproject/subprojects/test-subproject.wrap b/subprojects/subproject/subprojects/test-subproject.wrap
--- a/subprojects/subproject/subprojects/test-subproject.wrap	1970-01-01 01:00:00.000000000 +0100
+++ b/subprojects/subproject/subprojects/test-subproject.wrap	2025-11-03 19:28:42.081190024 +0100
@@ -0,0 +1,7 @@
+[wrap-file]
+directory = libfoobar
+source_filename = foobar-1.0.tar.gz
+
+[provide]
+dependency_names=foobar
+foobar=foobar_dep
```

</details>

Minimal reproducible example. Works in meson 1.8.5, fails in meson 1.9.0. The wrap file `subprojects/test.wrap` conflicts with the wrap file `subprojects/subproject/subprojects/test-subproject.wrap`.

<details>
<summary>logs from 1.8.5</summary>

```
The Meson build system
Version: 1.8.5
Source dir: /home/morse/codeworks/wraptest
Build dir: /home/morse/codeworks/wraptest/buildDir
Build type: native build
Project name: wraptest
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject subproject 

subproject| Project name: subproject
subproject| Project version: undefined
subproject| Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
subproject| Found CMake: /usr/bin/cmake (3.31.6)
subproject| Run-time dependency foobar found: NO (tried pkgconfig and cmake)
subproject| Looking for a fallback subproject for the dependency foobar

Executing subproject subproject:test

test| Project name: foobar
test| Project version: undefined
test| Build targets in project: 0
test| Subproject test finished.

subproject| Dependency foobar from subproject subprojects/libfoobar found: YES undefined
subproject| Build targets in project: 0
subproject| Subproject subproject finished.

Build targets in project: 0

wraptest undefined

  Subprojects
    subproject: YES
    test      : YES (from subproject)

Found ninja-1.13.1 at /usr/bin/ninja
```

</details>

<details>
<summary>logs from 1.9.1 (same as 1.9.0)</summary>

```
The Meson build system
Version: 1.9.1
Source dir: /home/morse/codeworks/wraptest
Build dir: /home/morse/codeworks/wraptest/buildDir
Build type: native build
Project name: wraptest
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject subproject 


subprojects/subproject/meson.build:1:0: ERROR: Multiple wrap files provide 'foobar' dependency: test-subproject and test

A full log can be found at /home/morse/codeworks/wraptest/buildDir/meson-logs/meson-log.txt
```

</details>

**Comment by radistmorse** [comment]
@bonzini I made the bisect and found the offending commit

https://github.com/mesonbuild/meson/commit/56e84d35deef8aea2b0beda2ec14ca22334a7f0f

Or more precisely, the changes to  the `_merge_wraps` function. Or even more precisely, the calling of the `add_wrap` function during the merging instead of previous manual additions.

On one hand, it doesn't look like an error, the call of `add_wrap` was intentional, and the function is explicitly designed to fail on duplications. On the other hand, the commit description doesn't mention duplicated wraps, and the resulting behavious was probably not intended.

It wouldn't be a problem to revert the use of `add_wrap` back to the manual insertion, but I gues this is a design question now: which *is* the intended behaviour, and how do you want to deal with duplicated wraps.

I also found out that the problem disappears if the duplicated wrap files have the same name, since the `wraps` dictionary uses it as a key, and the wrap files with identical names get ignored.

**Comment by radistmorse** [comment]
I see that in the meson documentation there is this line:

All wrap files must have a name of `<project_name>.wrap` form and be in `subprojects` dir.

So I guess this is incorrect to have wrap files with different names to describe the same project, and the error is thus the intended behaviour. But in this case it should probably be denoted in the changelog, that differently named wrap files providing the same `dependency_names` will cause an error starting with 1.9.0.

**Comment by georgev93** [comment]
This is fixed in 1.10.0, apparently? I tried it out, and it seems to be working now, but there are no PRs or commits linking to this issue...

**Comment by bonzini** [comment]
Great, if it's fixed I can try the reverse bisection.

**Comment by radistmorse** [comment]
My minimal example still doesn't work on 1.10.0, and I don't see any relevant changes to the `wrap.py` file.
