### ISSUE TITLE
meson traceback with RuntimeError("generator didn't yield")

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#2689]
Originally reported as https://bugzilla.redhat.com/show_bug.cgi?id=1517508.
Looks like a bug in the context manager or the way it is called.

Description of problem:
```console
$ninja -C build
ninja: Entering directory `build'
[0/1] Regenerating build files.
The Meson build system
Version: 0.43.0
Source dir: /home/zbyszek/src/systemd
Build dir: /home/zbyszek/src/systemd/build
Build type: native build
Project name: systemd
Native C compiler: ccache cc (gcc 7.2.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program tools/meson-check-compilation.sh found: YES (/home/zbyszek/src/systemd/tools/meson-check-compilation.sh)
Program c++ found: YES (/usr/bin/c++)
Native C++ compiler: ccache c++ (gcc 7.2.1)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 352, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 147, in generate
    self._generate(env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 195, in _generate
    intr.run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2785, in run
    super().run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 170, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 164, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 205, in evaluate_statement
    return self.evaluate_foreach(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 342, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 170, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 164, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 185, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 232, in evaluate_if
    result = self.evaluate_statement(i.condition)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 179, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 415, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 96, in method_call
    return self.methods[method_name](args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1018, in has_argument_method
    result = self.compiler.has_argument(args[0], self.environment)
  File "/usr/lib/python3.6/site-packages/mesonbuild/compilers/compilers.py", line 709, in has_argument
    return self.has_multi_arguments([arg], env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/compilers/c.py", line 747, in has_multi_arguments
    return self.compiles('int i;\n', env, extra_args=args)
  File "/usr/lib/python3.6/site-packages/mesonbuild/compilers/c.py", line 309, in compiles
    with self.compile(code, args.to_native(), mode) as p:
  File "/usr/lib64/python3.6/contextlib.py", line 83, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
FAILED: build.ninja 
/usr/bin/python3 /usr/bin/meson --internal regenerate /home/zbyszek/src/systemd /home/zbyszek/src/systemd/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```
Version-Release number of selected component (if applicable):
meson-0.43.0-1.fc26.noarch
python3-3.6.3-2.fc26.x86_64

How reproducible:
This is the first time I've seen this. If I repeat the command, I get the tb every time.

**Comment by nirbheek** [comment]
This is a bug with how we catch `OSError` inside `mesonbuild/compilers/compilers.py:Compiler.compile()`. The `pass` there is wrong:

```python
try:
    with tempfile.TemporaryDirectory() as tmpdirname:
        [do stuff that creates a subprocess.Popen object]
        yield p # popen object
except (PermissionError, OSError):
    # Ignore errors in deleting the temporary directory
    pass
```

So when there's an exception, we won't yield anything and get that `RuntimeError`. This bug happened because we moved to nested context managers instead of manually handling file object state several months ago.

The fix is to figure out a way to yield even when deleting the temporary file fails.

**Comment by dcbaker** [comment]
Can't we just return `None` at the end of the function?

**Comment by nirbheek** [comment]
The case we need to handle here is when we get an exception when Python tries to delete the temporary directory, which we don't care about. In that case, we still want to `yield p` and ignore the exception.

**Comment by nirbheek** [comment]
This was a Python 3.7 regression and has been fixed already.

**Comment by mingwandroid** [comment]
I am still seeing this on MSYS2 with Python 3.8.5. Here are the details:

```
meson --version
0.54.3
```

```
/mingw64/bin/python --version
Python 3.8.5
```

```
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 4372, in run
    super().run()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 465, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 490, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 483, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 528, in evaluate_statement
    self.evaluate_foreach(cur)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 761, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 490, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 483, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 506, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 581, in evaluate_if
    result = self.evaluate_statement(i.condition)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 500, in evaluate_statement
    return self.method_call(cur)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 895, in method_call
    return obj.method_call(method_name, args, self.kwargs_string_keys(kwargs))
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 39, in method_call
    return method(args, kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 1629, in has_argument_method
    return self.has_multi_arguments_method(args, kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 1634, in has_multi_arguments_method
    result, cached = self.compiler.has_multi_arguments(args, self.environment)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/compilers/mixins/clike.py", line 1112, in has_multi_arguments
    return self.has_arguments(args, env, code, mode='compile')
  File "C:/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/compilers/mixins/gnu.py", line 362, in has_arguments
    with self._build_wrapper(code, env, args, None, mode, disable_cache=False, want_output=True) as p:
  File "C:/msys64/mingw64/lib/python3.8/contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
```
