### ISSUE TITLE
False positives in clang-cl for stpcpy(), strcasecmp() and strncasecmp()

### ISSUE THREAD

**Issue by fanc999** [mesonbuild/meson#5628]
Hi,

When trying to build GLib with clang-cl (against Visual Studio 2019 with its Windows SDK), I have false positives for stpcpy(), strcasecmp() and strncasecmp(), which will result in linking the glib-2.0-0.dll to fail.  I will try to enclose the portions of the meson-logs.txt that are relevant.

With blessings, thank you!

**Comment by fanc999** [comment]
The snippets are as follows:

[stpcpy.txt](https://github.com/mesonbuild/meson/files/3375599/stpcpy.txt)
[strcasecmp-strncasecmp.txt](https://github.com/mesonbuild/meson/files/3375604/strcasecmp-strncasecmp.txt)

With blessings, thank you!

**Comment by jpakkane** [comment]
So is the issue that it detects stpcopy when it should not? Because the error message has this:

```
C:\Users\fanc999\AppData\Local\Temp\tmpqizhguiu\testfile.c(9,32): note: include the header <string.h> or explicitly provide a declaration for 'stpcpy'
```

This would indicate that stpcopy is provided by the system. Can you run the check with including `string.h` with the prefix kwarg?

**Comment by nirbheek** [comment]
We run two separate checks when doing has_function: one where we look for the function, and another where we look for it as a builtin. I think what's happening is that clang-cl is providing the builtin versions, which we detect, but they're not available as normal functions. Our assumption is that is `__builtin_stpcpy` is available, `stpcpy` is also available, which is wrong.

This is something we need to fix in general because it trips up various other compilers too.

**Comment by ePirat** [comment]
> So is the issue that it detects stpcopy when it should not? Because the error message has this:
> 
> ```
> C:\Users\fanc999\AppData\Local\Temp\tmpqizhguiu\testfile.c(9,32): note: include the header <string.h> or explicitly provide a declaration for 'stpcpy'
> ```
> 
> This would indicate that stpcopy is provided by the system. Can you run the check with including `string.h` with the prefix kwarg?

You will get this message (in error) even if the actual standard library you are linking with lacks this function. It's quite confusing, yes.

**Comment by lazka** [comment]
This should be fixed since d7e20b1543499 (0.54.2). Fixed in the sense that clang and gcc should give the same result now.

**Comment by amezin** [comment]
Still can't build GLib with clang-cl because of str[n]casecmp: https://gitlab.gnome.org/GNOME/glib/-/issues/2337 (Meson 0.57.1)

**Comment by bonzini** [comment]
Closing as duplicate since #3740 tracks limitations in the detection of functions.
