### ISSUE TITLE
iOS simulator cross compiling is broken since Meson 0.54.0

### ISSUE THREAD

**Issue by tbodt** [mesonbuild/meson#7111]
**Describe the bug**
iOS simulator binaries can't be run on the host. My cross file specifies this with `needs_exe_wrapper = true`.

**To Reproduce**
The meson.build file is irrelevant, it only has to specify the C language. For example, `project('repro', 'c')`.

Cross file:
```
[binaries]
c = 'clang'
ar = 'ar'

[host_machine]
system = 'darwin'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
c_args = ['-arch', 'x86_64']
needs_exe_wrapper = true
```

Install Xcode, then run meson with these environment variables. SDKROOT may have to be updated depending on your Xcode version, this works for Xcode 11.4.1.
```sh
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk
export CC_FOR_BUILD="env -u SDKROOT clang"
```

**Expected behavior**
Expected Meson to succeed, instead got
```
meson.build:1:0: ERROR: Executables created by c compiler ccache cc are not runnable.
```

If I install meson 0.53.1 (and use CC instead of CC_FOR_BUILD due to #6806) it works. If I change the `'-arch'` in the cross file to arm64 and use the iPhone SDK instead of the simulator SDK, it works.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? cross build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): macOS 10.15.4
* what Python version are you using e.g. 3.8.0: 3.7.6
* what `meson --version`: 0.54.0
* what `ninja --version` if it's a Ninja build: 1.9.0

**Comment by tbodt** [comment]
Forgot to mention that I bisected to #6636 (cc @jon-turney)

**Comment by jon-turney** [comment]
Interesting.  What is the 'cc' in your path?

**Comment by tbodt** [comment]
It is clang.

**Comment by jon-turney** [comment]
> It is clang.

What is the default target for that clang? macOS or iPhone Simulator?

> The meson.build file is irrelevant, it only has to specify the C language. For example, `project('repro', 'c')`.

Can you provide a meson-log.txt for that trivial project when it fails?

>  If I change the `'-arch'` in the cross file to arm64 and use the iPhone SDK instead of the simulator SDK, it works.

Hmm.. that's a confusing detail.

**Comment by tbodt** [comment]
> What is the default target for that clang? macOS or iPhone Simulator?

As far as I can tell that depends on the SDKROOT environment variable, hence the setting for CC_FOR_BUILD.

> Can you provide a meson-log.txt for that trivial project when it fails?

<details>

```
Build started at 2020-05-09T21:27:22.347228
Main binary: /usr/local/opt/python/bin/python3.7
Build Options: '--cross-file cross.txt'
Python system: Darwin
The Meson build system
Version: 0.54.999
Source dir: /Users/tbodt/Developer/projects/meson/repro
Build dir: /Users/tbodt/Developer/projects/meson/repro/build
Build type: cross build
None of 'PKG_CONFIG_PATH_FOR_BUILD' are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
Project name: repro
Project version: undefined
Using 'CC_FOR_BUILD' from environment with value: 'env -u SDKROOT clang'
None of 'CFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'LDFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CPPFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CC_LD_FOR_BUILD' are defined in the environment, not changing global flags.
Sanity testing C compiler: env -u SDKROOT clang
Is cross compiler: False.
Sanity check compiler command line: env -u SDKROOT clang /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.c -o /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.exe -pipe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.exe
C compiler for the build machine: env -u SDKROOT clang (clang 11.0.3 "Apple clang version 11.0.3 (clang-1103.0.32.59)")
C linker for the build machine: env -u SDKROOT clang ld64 556.6
None of 'AR_FOR_BUILD' are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
Sanity testing C compiler: clang
Is cross compiler: False.
Sanity check compiler command line: clang /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.c -o /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.exe -arch x86_64 -pipe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/tbodt/Developer/projects/meson/repro/build/meson-private/sanitycheckc.exe

meson.build:1:0: ERROR: Executables created by c compiler clang are not runnable.
```

(I honestly don't know why it now says `clang` instead of `ccache cc` like it did last time...)
</details>

> Hmm.. that's a confusing detail.

I did a little print debugging and it looks like it's getting confused about whether it can run host-compiled programs when the host architecture is the same as build. The needs_exe_wrapper = true setting should override this, but apparently doesn't.

**Comment by tbodt** [comment]
BTW my real use case is building https://github.com/ish-app/ish. If there are any problems reproducing with the case I've given, trying to build this app in Xcode for the simulator should repro it.

**Comment by jon-turney** [comment]
>  it looks like it's getting confused about whether it can run host-compiled programs when the host architecture is the same as build. The needs_exe_wrapper = true setting should override this, but apparently doesn't.

Yup.

>  Sanity testing C compiler: clang
>  Is cross compiler: False.
> [...]
>  meson.build:1:0: ERROR: Executables created by c compiler clang are not runnable.

It's worse because we'd only use the exe_wrapper if decided it's a cross-compile, which we don't here.

> If I change the `'-arch'` in the cross file to arm64 and use the iPhone SDK instead of the simulator SDK, it works

... because we compare the machine details to determine it if it's a cross-compile.

https://github.com/mesonbuild/meson/blob/d298a00afb4286ce7dfae231c311500e0d3de728/mesonbuild/environment.py#L902

I don't understand why this isn't just `is_cross = self.is_cross_build()`.  @Ericson2314 ?

Possibly relevant: #6361

**Comment by jpakkane** [comment]
> I don't understand why this isn't just is_cross = self.is_cross_build()

Because there is a difference between cross building and the cross compiler. When cross compiling we also look up the native compiler. We need to distinguish between the two cases, but arguably the "crossness" could come from the called as an argument.

That being said I think we merged some fixes for this. Can you test if this is fixed in master?

**Comment by Ericson2314** [comment]
https://github.com/mesonbuild/meson/pull/6933/files this one seems especially relevant, but isn't merged yet.

**Comment by jpakkane** [comment]
Can you test if #6933 fixes this issue for you?

**Comment by tbodt** [comment]
#6933 does in fact fix it!

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/6933.

**Comment by jon-turney** [comment]
> #6933 does in fact fix it!

Great.  

I notice that even after that, we still have some uses of `matches_build_machine`.  This issue seems to point out that comparing MachineInfo is not a safe thing to do, as machines can differ in ways which aren't currently recorded in MachineInfo, as is the case here for macOS and iPhoneSimulator (also discussed in #6361).
