### ISSUE TITLE
"Unsupported linker" trying to cross compile for windows using mingw32

### ISSUE THREAD

**Issue by duncanmcn** [mesonbuild/meson#8647]
**Describe the bug**

Trying to cross compile a simple program using mingw32, on linux, targeting windows.

Receive the following error:

`meson.build:1:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not x86_64-w64-mingw32-ld.`

**To Reproduce**

Any toy project is fine (e.g. meson init -l cpp)

Here is my cross_file.txt:

```
[binaries]
exe_wrapper = 'wine'
c = 'x86_64-w64-mingw32-gcc'
cpp = 'x86_64-w64-mingw32-cpp'
cpp_ld = 'x86_64-w64-mingw32-ld'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```

**Expected behavior**

Expecting to be able to select the mingw32 linker without complaint

**system parameters**

Cross building on ubuntu targeting x64 windows.

python 3.8.5
meson 0.57.999

**Comment by dcbaker** [comment]
The way I implemented the linkers is confusing, I'm sorry about that.

Meson always prefers to use the compiler as a linker driver if possible (basically for all compilers except MSVC). This means that for gcc and clang `cpp_ld` should be an argument to `-fuse-ld=`, we're going to cal `x86_64-w64-gcc` to do the linking. 

You're also passing `cpp`, the "C Pre Processor", but Meson wants `C++` there.

**Comment by duncanmcn** [comment]
Still don't fully understand sorry. I've tried a variety of different options inside the cross file, but now I get 

```ERROR: Unable to detect linker for compiler "x86_64-w64-mingw32-cpp -Wl,--version"```

when using

```
[binaries]
exe_wrapper = 'wine'
cpp = 'x86_64-w64-mingw32-cpp'
c++_ld = 'x86_64-w64-mingw32-cpp'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```

Would you be able to suggest a change to the cross file that might work?

**Comment by eli-schwartz** [comment]
None of this is related to what dcbaker said.

But, the long and short of it is,

```ini
[binaries]
exe_wrapper = 'wine'
cpp = 'x86_64-w64-mingw32-cpp'
```
this makes no sense, the cpp option is for the C++ programming language and you are passing the GCC preprocessor binary, try the g++ binary instead.

(The fact that meson has incorrectly named cxx as "cpp", and the option should be `cxx = ` but isn't, is beside the point. It is what it is, we just need to deal with it.)

```ini
c++_ld = 'x86_64-w64-mingw32-cpp'
```
This is double wrong, `c++_ld` is not a meson option. And you're completely ignoring

> for gcc and clang `cpp_ld` should be an argument to `-fuse-ld=`

Can you run `gcc -fuse-ld=x86_64-w64-mingw32-cpp` ???

**Comment by duncanmcn** [comment]
so in summary: 

```
[binaries]
exe_wrapper = 'wine'
cpp = 'x86_64-w64-mingw32-g++'
c++_ld = 'gold'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```

**Comment by autoantwort** [comment]
Hi, I have the exact same problem and tried to fix it with:
```
[binaries]
c = '/usr/src/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.shared.posix-gcc'
cpp = '/usr/src/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.shared.posix-g++'
```
and 
```
[properties]
c_args = ['-O3', '-DNDEBUG', '-I"/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include"', '-fuse-ld="/usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-ld"']
cpp_args = ['-O3', '-DNDEBUG', '-I"/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include"', '-fuse-ld="/usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-ld"']
```

But then I get the following error:
```
../src/e550234ca0-59b6eda119.clean/meson.build:1:0: ERROR: Unable to detect linker for compiler "/usr/src/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.shared.posix-gcc -Wl,--version -g -I"/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include" -fuse-ld="/usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-ld""
stdout: 
stderr: x86_64-w64-mingw32.shared.posix-gcc: error: unrecognized command-line option '-fuse-ld="/usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-ld"'

```

**Comment by dcbaker** [comment]
@autoantwort gcc/g++ doesn't understand full paths for linkers. When it's configured, it's configured with a linker driver to invoke. what `-fuse-ld` does it tells gcc "when you invoke the ld you konw about, use X backend." where X us usually bfd, gold, or lld.
