### ISSUE TITLE
ERROR: Argument gobject/glib-mkenums of type File is not held by an ObjectHolder.

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#8904]
**Describe the bug**
master branch fails to build glib 2,64.1
```
gobject/meson.build:99:0: ERROR: Argument gobject/glib-mkenums of type File is not held by an ObjectHolder.

    This is a Meson bug and should be reported!
```

**To Reproduce**
1. get the source code of glib 2.64.1 (or switch to git tag 2.64.1)
2. run `meson build` using latest meson from master branch
3. above error

**Expected behavior**
no error

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) arch linux (parabola)
* what Python version are you using e.g. 3.8.0: 3.9.5
* what `meson --version` latest master branch
* what `ninja --version` if it's a Ninja build N/A

**Comment by xclaesse** [comment]
@mensinda I get this error in GStreamer, I believe it's also related somehow to ObjectHolder refactoring: `subprojects/gstreamer/gst/meson.build:275:2: ERROR: Gir target must be an executable or library`

**Comment by mensinda** [comment]
Seems like there is a problem with `set_variable`, where the variables are not handled correctly

**Comment by mensinda** [comment]
Should be fixed with #8905.

**Comment by xclaesse** [comment]
> Should be fixed with #8905.

That does not fix the problem in gst-build, I'll report it separately.

**Comment by mensinda** [comment]
The gst-build issue will be fixed in a separate PR and is now tracked in #8907.
