### ISSUE TITLE
Regression: Error in GStreamer configuration

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#8907]
I get this error during gst-build configuration, I believe it's ObjectHolder refactoring: `subprojects/gstreamer/gst/meson.build:275:2: ERROR: Gir target must be an executable or library`.

**Comment by xclaesse** [comment]
Bisected, the first that broke gst-build is `8f997efc8 decorators: Add not_set_warning to KwargInfo`, with that commit I get meson crash because of typing issues.

**Comment by mensinda** [comment]
I have looked at the commit and this doesn't make any sense *at all*. Then again, I didn't make the PR particularly easy to bisect, since I didn't actually check the commits :(

The problem is caused by `orcc` using `override_find_program` and `gst-plugins-base` using `find_program('orcc').found()`. Thus `find_program('orcc')` now returns an executable which doesn't have the `.found()` method.

**Comment by mensinda** [comment]
@xclaesse Are you sure that you have used the latest changes from my branch? I am unable to reproduce this bug locally (after I have fixed the unrelated `orcc` bug).

**Comment by xclaesse** [comment]
Still happening with both PR #8908 and #8905 applied.

Here is the backtrace I get with `MESON_FORCE_BACKTRACE=1`:
```
subprojects/gstreamer/gst/meson.build:275:2: ERROR: Gir target must be an executable or library

A full log can be found at /home/xclaesse/programmation/gst-build/builddir/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "/home/xclaesse/.local/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/home/xclaesse/programmation/meson/mesonbuild/mesonmain.py", line 321, in main
    return run(sys.argv[1:], launcher)
  File "/home/xclaesse/programmation/meson/mesonbuild/mesonmain.py", line 311, in run
    return CommandLineParser().run(args)
  File "/home/xclaesse/programmation/meson/mesonbuild/mesonmain.py", line 223, in run
    return options.run_func(options)
  File "/home/xclaesse/programmation/meson/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/home/xclaesse/programmation/meson/mesonbuild/msetup.py", line 184, in generate
    self._generate(env)
  File "/home/xclaesse/programmation/meson/mesonbuild/msetup.py", line 223, in _generate
    intr.run()
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 2421, in run
    super().run()
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 132, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_statement
    self.evaluate_foreach(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 451, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_statement
    return self.evaluate_if(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 257, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 165, in evaluate_statement
    self.assignment(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 910, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 549, in function_call
    res = func(node, func_args, kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 598, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 102, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 64, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 755, in func_subproject
    return self.do_subproject(args[0], 'meson', kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 832, in do_subproject
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 816, in do_subproject
    return self._do_subproject_meson(subp_name, subdir, default_options, kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 850, in _do_subproject_meson
    subi.run()
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 2421, in run
    super().run()
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 132, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 549, in function_call
    res = func(node, func_args, kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 598, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 102, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreter.py", line 1906, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_statement
    return self.evaluate_if(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 257, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 165, in evaluate_statement
    self.assignment(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 910, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_statement
    return self.method_call(cur)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/interpreterbase.py", line 593, in method_call
    return self._holderify(obj.method_call(method_name, args, kwargs))
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreter/interpreterobjects.py", line 764, in method_call
    ret = method(state, args, kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 598, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 598, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/interpreterbase/decorators.py", line 102, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/xclaesse/programmation/meson/mesonbuild/modules/gnome.py", line 822, in generate_gir
    girtargets = [self._unwrap_gir_target(arg, state) for arg in args]
  File "/home/xclaesse/programmation/meson/mesonbuild/modules/gnome.py", line 822, in <listcomp>
    girtargets = [self._unwrap_gir_target(arg, state) for arg in args]
  File "/home/xclaesse/programmation/meson/mesonbuild/modules/gnome.py", line 485, in _unwrap_gir_target
    raise MesonException('Gir target must be an executable or library')
mesonbuild.mesonlib.universal.MesonException: Gir target must be an executable or library
```

**Comment by xclaesse** [comment]
@mensinda maybe you don't have gobject-introspection installed?

**Comment by mensinda** [comment]
@xclaesse I had `gobject-introspection` installed and still couldn't reproduce the bug... I also can't reproduce it with our CI docker images. For reference reproduction:

```bash
./ci/ciimage/build.py -t testTTY arch
git clone https://github.com/GStreamer/gst-build.git
cd gst-build
../meson.py build
```

What `gst-build` version are you using? Are you on master? Could you show the output with this patch:

```diff
diff --git a/mesonbuild/modules/gnome.py b/mesonbuild/modules/gnome.py
index 0ae1c70ca..7be4660ad 100644
--- a/mesonbuild/modules/gnome.py
+++ b/mesonbuild/modules/gnome.py
@@ -482,7 +482,7 @@ class GnomeModule(ExtensionModule):
     def _unwrap_gir_target(self, girtarget, state):
         if not isinstance(girtarget, (build.Executable, build.SharedLibrary,
                                       build.StaticLibrary)):
-            raise MesonException('Gir target must be an executable or library')
+            raise MesonException(f'Gir target must be an executable or library but is "{girtarget}" of type {type(girtarget).__name__}')
 
         STATIC_BUILD_REQUIRED_VERSION = ">=1.58.1"
         if isinstance(girtarget, (build.StaticLibrary)) and \
```

**Comment by mensinda** [comment]
I have might suspicions what it might be, so could you also check if this patch fixes the issue:

```diff
diff --git a/mesonbuild/modules/gnome.py b/mesonbuild/modules/gnome.py
index 0ae1c70ca..51f2e6ece 100644
--- a/mesonbuild/modules/gnome.py
+++ b/mesonbuild/modules/gnome.py
@@ -480,9 +480,11 @@ class GnomeModule(ExtensionModule):
             return cflags, internal_ldflags, external_ldflags, external_ldflags_nodedup, gi_includes
 
     def _unwrap_gir_target(self, girtarget, state):
+        if isinstance(girtarget, build.BothLibraries):
+            girtarget = girtarget.get_preferred_library()
         if not isinstance(girtarget, (build.Executable, build.SharedLibrary,
                                       build.StaticLibrary)):
-            raise MesonException('Gir target must be an executable or library')
+            raise MesonException(f'Gir target must be an executable or library but is "{girtarget}" of type {type(girtarget).__name__}')
 
         STATIC_BUILD_REQUIRED_VERSION = ">=1.58.1"
         if isinstance(girtarget, (build.StaticLibrary)) and \
```

**Comment by xclaesse** [comment]
That was the problem indeed, but then it crash a little bit further. Clearly need to test gst-build with -Ddefault_library=both, it's a huge stress test :D
